- name: Ensure nginx is installed
  apt: 
    name: nginx  
    state: present

- name: Copy Nginx default config to sites-enabled
  template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  no_log: true
  notify: 
    - restart nginx
    - restart nginx exporter

- name: start nginx
  service:
    name: nginx
    state: started 
    enabled: true

- name: Install exporter
  apt:
    name: prometheus-nginx-exporter
    state: present

- name: Run the nginx exporter
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
