- name: Ensure nginx is installed and in working state
  apt: 
    name: nginx  

- name: Copy Nginx default config to sites-enabled
  template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started 
    enabled: true

- name: Install exporter
  apt:
    name: prometheus-nginx-exporter

- name: Run the nginx exporter
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
