- name: Ensure nginx is installed and in working state
  apt: 
    name: nginx  

- name: Copy Nginx default config to sites-enabled
  copy:
    src: ../files/default
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started 
    enabled: true
