- name: Install haproxy
  apt:
    name: haproxy
    state: present

- name: Copy the Haproxy config
  template:
    src: haproxy.cnf.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0600
  notify: Restart Haproxy
  no_log: true

- name: Start the service
  service:
    name: haproxy
    state: started
    enabled: true

- name: Install prometheus-haproxy-exporter using APT
  apt:
    name: prometheus-haproxy-exporter
    state: present

- name: Configure haproxy.scrape-uri in /etc/default/prometheus-haproxy-exporter
  template:
    src: prometheus_haproxy
    dest: /etc/default/prometheus-haproxy-exporter
  notify: restart prometheus-haproxy-exporter
  no_log: true

- name: Start haproxy exporter
  service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: yes

- name: Create CNAME records for HAproxy instances
  community.general.nsupdate:
    key_name: "nsupdate.key"
    server: "{{ groups['dns_primary'][0] }}"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_secret }}"
    zone: "{{ startup_name }}"
    state: present
    type: "CNAME"
    value: "{{ hostvars[groups['haproxy'][item]]['ansible_hostname'] }}"
    record: "lb-{{ item + 1 }}"
  loop: "{{ range( groups['haproxy'] | length ) }}"
  no_log: true