---
  - name: Install influxdb
    become: yes
    get_url:
      url: "https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb"
      dest: "/tmp/influxdb_1.8.10_amd64.deb"

  - name: Dpkg InfluxDB
    apt:
      deb: "/tmp/influxdb_1.8.10_amd64.deb"

  - name: Ensure InfluxDB is enabled and running 
    service:
      name: influxdb 
      state: started
      enabled: true
  
  - name: Change the config for Influxdb
    copy:
      src: ../files/influx.conf
      dest: /etc/influxdb/influxdb.conf
    notify: restart influxdb

  - name: Download and install Telegraf
    get_url:
      url: "https://dl.influxdata.com/telegraf/releases/telegraf_1.28.2-1_amd64.deb"
      dest: "/tmp/telegraf.deb"

  - name: Install Telegraf
    apt:
      deb: "/tmp/telegraf.deb"
      state: present

  - name: Configure Telegraf for syslog input and InfluxDB output
    copy:
      src: ../files/telegraf.conf
      dest: /etc/telegraf/telegraf.conf

  - name: Restart Telegraf service
    service:
      name: telegraf
      state: restarted
      enabled: yes

  - name: Download InfluxDB Stats Exporter binary
    get_url:
      url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
      dest: /usr/local/bin/influxdb_stats_exporter
      mode: 0755

  - name: Create systemd service for InfluxDB Stats Exporter
    copy:
      src: ../files/influxdb.service.conf
      dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
      mode: 0644
    notify: restart influxdb-stats-exporter

  - name: Restart Prometheus and InfluxDB Stats Exporter
    service:
      name: "{{ item }}"
      state: restarted
    loop:
      - prometheus
      - prometheus-influxdb-stats-exporter
