---
- name: Create Grafana directories
  file:
    path: "/opt/grafana/{{ item }}"
    state: directory
  loop:
    - provisioning/dashboards
    - provisioning/datasources

- name: Copy the config
  template:
    src: ../templates/grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true
  notify:
   - restart grafana

- name: Pull Grafana Docker image
  community.docker.docker_image:
    name: grafana/grafana
    source: pull

- name: Start Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart_policy: always
    ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana