---
- name: Install uWSGI packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - uwsgi
    - uwsgi-plugin-python3
    - python3-pymysql

- name: Configure uWSGI for AGAMA application
  copy:
    src: ../files/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uWSGI service


- name: uWSGI service
  service:
    name: uwsgi
    state: started
    enabled: true
