---
- name: Install uWSGI packages
  apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3
    - python3-pymysql
    state: present

- name: Configure uWSGI for AGAMA application
  template:
    src: ../templates/agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama 
    mode: 0600
  no_log: true 
  notify: Restart uWSGI service


- name: uWSGI service
  service:
    name: uwsgi
    state: started
    enabled: yes
