- name: Install influxdb
  bacome: yes
    get_url:
    url: "https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb"
    dest: "/tmp/influxdb_1.8.10_amd64.deb"

- name: Dpkg InfluxDB
  apt:
    deb: "/tmp/influxdb_1.8.10_amd64.deb"
