{
 "title": "MySQL dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Replication Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "__auto"
    },
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Read Only",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL ID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}