---

- name: Shut down systemd-resolved
  become: yes
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Change resolv.conf on all VMs
  become: yes
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  no_log: true