- name: Install mysql
  apt:
    name: mysql-server
    state: present

- name: copy the mysql config file and restart mysql server
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
    mode: 0644
  notify: restart mysql
  no_log: true

- name: Start mysql
  service:
    name: mysql
    state: started 
    enabled: true

- name: Install required Python Library
  apt:
    name: python3-pymysql  
    state: present

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica
    
- name: MySQL user
  community.mysql.mysql_user:
    host: "%"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present 
  no_log: yes

- name: Create MySQL exporter user
  mysql_user:
    name: "{{ mysql_prometheus_user }}"
    password: "{{ mysql_prometheus_pass }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Install Exporter 
  apt:
    name: prometheus-mysqld-exporter
    state: present

- name: Update the MySQL exporter
  copy:
    src: ../files/mysql_exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify: restart mysql-exporter
  no_log: true

- name: Copy the config file 
  template:
    dest: /var/lib/prometheus/.my.cnf
    src: my.cnf.j2
  no_log: true
  notify: restart mysql-exporter

- name: Start Mysql exporter
  service: 
    name: prometheus-mysqld-exporter
    state: started
    enabled: true

# ====== BACKUP ======

- name: Ensure that mysql directory exists 
  file:
    path: /home/backup/mysql
    state: directory 
    owner: backup 
    group: backup 
    mode: '0755'

- name: Create MySQL user named backup with required privileges
  mysql_user:
    name: backup
    password: "{{ mysql_backup_user_password }}" 
    priv: "agama.*:LOCK TABLES,SELECT"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Ensure /home/backup/.my.cnf file is created
  template:
    src: backup_my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: '0600'
  no_log: true

- name: Ensure user backup can create MySQL dumps without errors
  command: "sudo -u backup sh -c 'mysqldump agama >/dev/null; echo $?'"
  register: dump_result
  changed_when: "dump_result.rc != 0"

- name: Fail if the dump command did not execute successfully
  fail:
    msg: "Error running mysqldump command. Check MySQL user privileges and .my.cnf configuration."
  when: dump_result.rc != 0

- name: Schedule MySQL backups with Cron
  template:
    src: mysql_backup_cron.j2
    dest: /etc/cron.d/mysql_backup
  no_log: true


# ====== REPLICATION ======

- name: Create MySQL user named replica with required privileges
  mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replica_user_password }}" 
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Read only mode for the Replica MySQL host
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: Create CNAME records for MySQL instances 1
  community.general.nsupdate:
    key_name: "nsupdate.key"
    server: "{{ groups['dns_primary'][0] }}"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_secret }}"
    zone: "{{ startup_name }}"
    state: present
    type: "CNAME"
    value: "{{ hostvars[groups['db_servers'][item]]['ansible_hostname'] }}"
    record: "mysql-{{ item + 1 }}"
  loop: "{{ range( groups['db_servers'] | length ) }}"
  no_log: true
