- name: restart nginx
  service:
    name: nginx
    state: restarted 
    enabled: true

- name: restart nginx exporter
  service:
    name: prometheus-nginx-exporter
    state: restarted 
    enabled: true
  
