{
 "title": "Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DNS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MYSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NGINX - kovalart-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"kovalart-1:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX - kovalart-2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"kovalart-2:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 4 },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS A Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MYSQL Selects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 11 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"SELECT\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}