---

  - name: Create "pinger" user
    user:
      name: pinger

  - name: Create a directory /etc/pinger
    file:
      path: /etc/pinger
      state: directory

  - name: Copy service to destination 
    copy: 
      src: ../files/pinger.sh
      dest: /usr/local/bin/pinger
      mode: 0777

  - name: Copy Pinger service file
    copy: 
      src: ../files/pinger.service
      dest: /etc/systemd/system/
      mode: 0777
    
  - name: Copy Pinger.conf file 
    copy: 
      src: ../files/pinger.conf
      dest: /etc/pinger/pinger.conf
      mode: 0777

  - name: Restart daemon
    systemd:
      daemon_reload: true