---

- name: restart influxdb-stats-exporter
  service:
    name: prometheus-influxdb-stats-exporter
    state: restarted
    enabled: true

- name: restart influxdb
  service:  
    name: influxdb
    state: restarted
    enabled: true

- name: restart telegraf
  service:  
    name: telegraf
    state: restarted
    enabled: true