---

- name: Install Prometheus
  apt:
    name: prometheus
    state: present

- name: Copy Prometheus Configuration
  template:
    src: prometheus_config.yaml.j2
    dest: /etc/prometheus/prometheus.yml
  no_log: true
  notify:
    - restart prometheus

- name: Copy Prometheus service configuration
  template:
    src: prom.service.j2
    dest: /etc/default/prometheus
  no_log: true
  notify:
    - restart prometheus

- name: Start the prometheus 
  service:
    name: prometheus
    state: started
    enabled: true

- name: Create CNAME record for prometheus
  community.general.nsupdate:
    key_name: "nsupdate.key"
    server: "{{ groups['dns_primary'][0] }}"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_secret }}"
    zone: "{{ startup_name }}"
    state: present
    record: "prometheus"
    type: "CNAME"
    value: "{{ hostvars[groups['prometheus'][0]]['ansible_hostname'] }}"
  no_log: true