- name: restart mysql
  service:
    name: mysql
    state: restarted
  become: yes

- name: restart mysql-exporter
  service: 
    name: prometheus-mysqld-exporter
    state: restarted
  become: yes

- name: reload cron 
  service: 
    name: cron
    state: restarted
  become: yes

