---
  - name: restart prometheus
    service:
      name: prometheus
      state: restarted
      enabled: true
  
  - name: restart nginx
    service:
      name: nginx
      state: restarted 
      enabled: true
