---

# --- Task 2 (Install Bind9)---
- name: Install Bind9
  become: yes
  become_method: sudo
  apt:
    name: 
      - bind9
      - libssl-dev
      - libuv1
      - perl
      - pkg-config
      - python3-dnspython
    state: present

# --- Task 3,4 (DNS forwarders and access rules) --- 
- name: Configure DNS forwarders
  become: yes
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

# --- Task 5 (Configure Master Zone) ---
- name: Configure Master Zone
  become: yes
  template:
    src: db.infocare.io.j2
    dest: /var/lib/bind/db.infocare.io
  notify: restart rndc

# --- Task 6

- name: Ensure Bind9 service is running and enabled
  become: yes
  systemd:
    name: bind9
    state: started

- name: Install Bind exporter
  apt:
    name: prometheus-bind-exporter