---

# --- Task 2 (Install Bind9)---
- name: Install Bind9
  become: yes
  become_method: sudo
  apt:
    name: 
      - bind9
      - libssl-dev
      - libuv1
      - perl
      - pkg-config
      - python3-dnspython
    state: present

# --- Task 3,4 (DNS forwarders and access rules) --- 
- name: Configure DNS forwarders
  become: yes
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Configure DNS 
  become: yes
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9

# --- Task 5 (Configure Master Zone) ---
- name: Configure Master Zone
  become: yes
  template:
    src: db.infocare.io.j2
    dest: /var/cache/bind/db.infocare.io
    force: no
  when:
    - inventory_hostname in groups['dns_primary']
  notify: 
    - restart rndc
    - restart bind9

# --- Task 6

- name: Ensure Bind9 service is running and enabled
  become: yes
  systemd:
    name: bind9
    state: started

- name: Install Bind exporter
  apt:
    name: prometheus-bind-exporter

- name: Create CNAME records for DNS instances
  community.general.nsupdate:
    key_name: "nsupdate.key"
    server: "{{ hostvars['kovalart-2']['ansible_default_ipv4']['address'] }}"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_secret }}"
    zone: "{{ startup_name }}"
    state: present
    type: "CNAME"
    value: "{{ item.target }}"
    record: "{{ item.service }}"
  with_items:
    - { service: "ns-1", target: "kovalart-1" }
    - { service: "ns-2", target: "kovalart-2" }
  when: "'kovalart-2' in inventory_hostname"
