---

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400       

- name: Install Prometheus nodes
  become: yes
  apt:    
    name:
      prometheus-node-exporter
    state: present

- name: Ensure the Node Exporters are started
  become: yes
  service: 
    name: prometheus-node-exporter
    state: started
    enabled: true 

- name: Ensure ca-certificates is installed with a specific version
  apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    state: present
  become: yes

# =========== RSYSLOG  ===========

- name: Install Rsyslog
  apt:
    name: rsyslog
    state: present

- name: Add the Rsyslog configuration for the Telegraf 
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf

# =========== BACKUP  ===========

- name: Create backup user
  user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    append: no
    groups: backup

- name: Ensure .ssh directory exists for backup user
  file:
    path: /home/backup/.ssh
    state: directory
    owner: backup
    group: backup
    mode: '0700'

- name: Generate SSH keypair for backup user
  openssh_keypair:
    path: /home/backup/.ssh/id_rsa
    owner: backup
    size: 2048

- name: Add backup server SSH key to known hosts
  template:
    src: backup_known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0600'
